Repository einschmidt/addon-caddy-2, pull requests merged in 2021-04, with the labels that each got.

#41 Remove port config
  caddy-2/config.json
Labels: breaking-change, maintenance

#42 Move-custom-caddy-checks
  caddy-2/rootfs/etc/services.d/caddy/run
  caddy-2/rootfs/usr/bin/caddy.sh
Labels: maintenance

#43 Add write rights to the share folder
  caddy-2/config.json
Labels: enhancement

#44 Upgrade caddy at startup
  caddy-2/config.json
  caddy-2/rootfs/usr/bin/caddy.sh
Labels: new-feature

#45 Rewrite Caddyfile check
  caddy-2/rootfs/usr/bin/caddy.sh
Labels: maintenance

#46 Prettify Caddyfile function
  caddy-2/config.json
  caddy-2/rootfs/usr/bin/caddy.sh
Labels: new-feature

#49 Fix caddy.sh
  caddy-2/rootfs/usr/bin/caddy.sh
Labels: maintenance

#50 Update DOCS.md
  caddy-2/DOCS.md
Labels: documentation

#53 Add pr-label action
  .github/workflows/pr-labels.yaml
Labels: ci

#54 Use `args` as an array not as a string
  caddy-2/rootfs/usr/bin/caddy.sh
Labels: bugfix

#55 Fix markdown errors
  caddy-2/DOCS.md
Labels: documentation

#56 Fix Shellcheck Error
  caddy-2/rootfs/usr/bin/caddy.sh
Labels: bugfix

#57 Add new line character to new workflow file
  .github/workflows/pr-labels.yaml
Labels: maintenance

#58 Prettify function
  caddy-2/rootfs/usr/bin/caddy.sh
Labels: maintenance
